### ISSUE TITLE
errors in dumplex copy

### ISSUE THREAD

**Issue by qiukeren** [jpillora/sockfwd#1]
```
go io.Copy(uconn, tconn)
io.Copy(tconn, uconn)
```

Here would cause error。

Suppose uconn closed before tconn or contraries。

Here.
http://stackoverflow.com/questions/32460618/golang-1-5-io-copy-blocked-with-two-tcpconn

**Comment by jpillora** [comment]
thanks for the report

**Comment by qiukeren** [comment]
fast.

and ,it's not potential,

it can be reappeared when transporting large files.(in my memory, large than 2K)

The file would be cut off.
